### ISSUE TITLE
Cluttered items in StartUp Location

### ISSUE THREAD

**Issue by hassan-hamidi** [mohammadKarimi/Riter#180]
If you open the "StartUp Location" form, you will see that the arrangement of items is messy.
I checked previous versions and found that this problem occurred after version 0.2.10.

**Comment by mohammadKarimi** [comment]
thanks, it has been fixed by version 2.0.11

**Comment by mohammadKarimi** [comment]
![image](https://github.com/user-attachments/assets/bd2dd864-886e-4338-be1e-0c96d4e76a33)

**Comment by mohammadKarimi** [comment]
If it is ok, let me know to close the issue.

**Comment by hassan-hamidi** [comment]
In the latest version (0.2.11) I still have this problem.
![Riter-Bug](https://github.com/user-attachments/assets/41283b4f-b639-4dc7-9b55-ca66b858960d)

**Comment by mohammadKarimi** [comment]
So, I have to rebuild it again. 
Plan this Issue to merge on v0.2.12
